cognitive_services:
  subscription_key: b40cd56a48c244f4b838488c0dda6eff
  faceapi_uri: westeurope.api.cognitive.microsoft.com
event_hubs:
  policy_secret: p+tHO7C9mjGiB6+PY9iAJf9qwjhaFhHeK9QpX2vkNIA=
  namespace: audience-analysis
  policy_name: RootManageSharedAccessKey
  hub_name: session-feed
app:
  log_level:  DEBUG