cognitive_services:
  subscription_key: <your key>
  faceapi_uri: westeurope.api.cognitive.microsoft.com
event_hubs:
  policy_secret: <primary key of event hub>
  namespace: audience-analysis
  policy_name: RootManageSharedAccessKey
  hub_name: <event hub name>

app:
  log_level:  DEBUG
  max_sessions: 8