cognitive_services:
  subscription_key: <fill>
  faceapi_uri: westeurope.api.cognitive.microsoft.com

event_hubs:
  policy_secret: <fill>
  namespace: audience-analysis
  policy_name: RootManageSharedAccessKey
  #hub_name: session-feed
  hub_name: faces-attr-counts

app:
  server_host: 0.0.0.0
  server_port: 5555
  log_level:  DEBUG
  max_sessions: 8
  resize_x: 200
  resize_y: 200

web_app:
  sku: B1
  region: northeurope
  app_name: aa-backend
  container_name: vykhand/aa-backend:latest
  resource_group: audience-analysis
  plan_name:  aa-backend-plan

redis:
  key: <fill>
  host: <fill>
  expire_sec: 3600

powerbi:
  user_name: <fill>
  password: <fill>
  client_id:  <fill>
  workspace_name: AA
  dataset_names: dataset-aa-sessions, dataset-audience-analysis